services:
  - type: web
    name: bot-vendas
    runtime: node
    region: sa-east-1
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 26.4.0
      - key: WEB_PORT
        value: 3000
      - key: NODE_ENV
        value: production
